apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  name: paws-psp
spec:
  requiredDropCapabilities:
    - ALL
  allowPrivilegeEscalation: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # GID for tools.paws only
      - min: 52771
        max: 52771
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      # UID for tools.paws only
      - min: 52771
        max: 52771
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'hostPath'
    - 'persistentVolumeClaim'
  allowedHostPaths:
    - pathPrefix: '/public/dumps'
      readOnly: true
    - pathPrefix: '/mnt/nfs'
      readOnly: true
    - pathPrefix: '/var/lib/sss/pipes'
      readOnly: false
    - pathPrefix: '/data/project'
      readOnly: false

---

# Cluster role which grants access to the paws pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: paws-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - paws-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paws-psp
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: paws-psp
subjects:
# For all service accounts in the prod (paws) namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:prod

---
# The deploy service account for the deploy hook needs a freer hand, I'm afraid
# We could also experiment with giving this lesser privs than this.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-hook-psp-binding
subjects:
- kind: ServiceAccount
  namespace: prod
  name: deploy
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
