apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    name: paws-public-legacy
    ingress.paws.wmcloud.org: legacy
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: $scheme://{{ .Values.pawspublic.ingress.host }}/$2
  name: paws-public-legacy
spec:
  rules:
  - host: {{ .Values.pawspublic.ingress.legacyHost | quote }}
    http:

      paths:
      # The backend portion is just there for the validator. It isn't used.
      - backend:
          serviceName: paws-public
          servicePort: 8000
        path: /paws-public(/|$)(.*)
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    name: paws-legacy
    ingress.paws.wmcloud.org: legacy
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: $scheme://{{ index .Values.jupyterhub.ingress.hosts 0 }}/$2
  name: paws-legacy
spec:
  rules:
  - host: {{ .Values.paws.ingress.legacyHost | quote }}
    http:
      paths:
      # The backend portion is just there for the validator. It isn't used.
      - backend:
          serviceName: paws-public
          servicePort: 8000
        path: /paws(/|$)(.*)
